### ISSUE TITLE
您好，这个Eigen打开一直有问题，应该怎么解决呢，谢谢

### ISSUE THREAD

**Issue by JJJIANGJIANG** [xxmy7/computer_graphics_practice#1]
没有成员Matrix3d、Vector4d
EigenBase不是模板等错误

**Comment by xxmy7** [comment]
需要你自己配置一下eigen这个库，将文件夹地址添加进项目的引用目录，我上传时项目里配置的就直接添加了，路径是绝对路径，所以可能和你的不一样，所以用不了，可以上网搜下如何配置eigen

**Comment by JJJIANGJIANG** [comment]
哦哦哦，谢谢。这个配置好了，但是rc文件一直打不来您知道是什么原因吗
错误	RC1110	could not open My2019302130011.rc	2019302130011	
D:\computer_graphics_practice-master\2019302130011\2019302130011\RC
十分感谢

**Comment by JJJIANGJIANG** [comment]
是不是res文件里的文件没有传上呀，麻烦您看一下

**Comment by xxmy7** [comment]
> 是不是res文件里的文件没有传上呀，麻烦您看一下

你说的对，应该是文件太大还是啥原因，当时没上传成功，也没管了，抱歉，如果你需要的话，你可以下载完整的一个压缩包（https://github.com/xxmy7/computer_graphics_practice/releases/download/v1/default.rar），已经发布到release了

**Comment by xxmy7** [comment]
> 是不是res文件里的文件没有传上呀，麻烦您看一下

你说的对，应该是文件太大还是啥原因，当时没上传成功，也没管了，抱歉，如果你需要的话，你可以下载完整的一个压缩包https://github.com/xxmy7/computer_graphics_practice/releases/download/v1/default.rar，已经发布到release了

**Comment by xxmy7** [comment]
你说的对，应该是文件太大还是啥原因，当时没上传成功，也没管了，抱歉，如果你需要的话，你可以下载完整的一个压缩包[https://github.com/xxmy7/computer_graphics_practice/releases/download/v1/default.rar](https://github.com/xxmy7/computer_graphics_practice/releases/download/v1/default.rar%EF%BC%8C%E5%B7%B2%E7%BB%8F%E5%8F%91%E5%B8%83%E5%88%B0release%E4%BA%86) 已经发布到release了

**Comment by JJJIANGJIANG** [comment]
好的好的，十分感谢！

**Comment by JJJIANGJIANG** [comment]
您好，有没有操作说明呐，能不能简要介绍一下种子填充入户操作呀，十分感谢！

**Comment by xxmy7** [comment]
左键点击构成多边形，右键确定闭合图形，然后点击多边形内可以进行种子填充，但这份代码写的好像没有判断点击的点是否在多边形内，你需要可以自己修改一下，然后似乎多边形太大了有时候会卡住
